server:
  port: 8337
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: uiot-service-things
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: uiot-service-things
  kafka:
    streams:
      application-id: "${spring.application.name}"
      bootstrap-servers: localhost:9092
  jackson:
    default-property-inclusion: non_null
springdoc:
  api-docs:
    path: /v3/api-docs
uiot:
  connectivity-integration-url: "http://localhost:8333/api/rooms/{roomUid}/things/{thingUid}/connectivity"
  system-events-topic: uiot-system-events
