services:

  kafka:
    image: apache/kafka:4.1.1
    ports:
      - "127.0.0.1:9092:9092"
    environment:
      CLUSTER_ID: 0
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:49092
      KAFKA_LISTENERS: EXTERNAL://:9092,INTERNAL://:29092,CONTROLLER://:49092
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092,INTERNAL://kafka:29092,CONTROLLER://kafka:49092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    volumes:
      - kafka_data:/var/lib/kafka/data:rw
    networks:
      - uiot
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  kafka-init-job:
    image: apache/kafka:4.1.1
    entrypoint: /bin/bash
    networks:
      - uiot
    depends_on:
      kafka:
        condition: service_healthy
    command: |
      -c "
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic uiot-accounting --replication-factor=1 --partitions=5 --bootstrap-server kafka:29092 &&
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic uiot-accounting-windows --replication-factor=1 --partitions=5 --bootstrap-server kafka:29092 &&
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic uiot-thing-events --replication-factor=1 --partitions=5 --bootstrap-server kafka:29092 &&
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic uiot-action-execution-events --replication-factor=1 --partitions=5 --bootstrap-server kafka:29092 &&
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic uiot-system-events --replication-factor=1 --partitions=5 --bootstrap-server kafka:29092 &&
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic uiot-service-history_thing-metadata --replication-factor=1 --partitions=5 --bootstrap-server kafka:29092 &&
        /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --topic uiot-service-history_keyed-thing-events --replication-factor=1 --partitions=5 --bootstrap-server kafka:29092
      "

  mongo:
    image: mongo:8.2.4
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongodb_data:/data/db:rw
      - ../uiot-config-mongo:/docker-entrypoint-initdb.d:ro
    networks:
      - uiot
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    image: rabbitmq:4.2.2-management-alpine
    ports:
      - "127.0.0.1:1883:1883"
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:8883:8883"
      - "127.0.0.1:15672:15672"
    volumes:
      - ../uiot-config-rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ../uiot-config-rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
      - ../uiot-config-rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - rabbitmq_data:/var/lib/rabbitmq:rw
    networks:
      - uiot
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  uiot-gateway:
    image: traefik:3.6.7
    ports:
      - "127.0.0.1:8330:80"
    volumes:
      - ./uiot-gateway/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./uiot-gateway/traefik_dynamic.toml:/etc/traefik/traefik_dynamic.toml:ro
    networks:
      - uiot
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--quiet", "http://localhost:80" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  uiot-swagger-ui:
    image: swaggerapi/swagger-ui:v5.31.0
    environment:
      URLS: '[
          { "url" : "/accounting/v3/api-docs",   "name" : "Accounting"   },
          { "url" : "/connectivity/v3/api-docs", "name" : "Connectivity" },
          { "url" : "/history/v3/api-docs",      "name" : "History"      },
          { "url" : "/rooms/v3/api-docs",        "name" : "Rooms"        },
          { "url" : "/rules/v3/api-docs",        "name" : "Rules"        },
          { "url" : "/things/v3/api-docs",       "name" : "Things"       }
        ]'
    networks:
      - uiot
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  uiot-service-accounting:
    image: malczuuu/uiot-service-accounting:${UIOT_VERSION}
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      SPRING_DATA_MONGODB_DATABASE: uiot-service-accounting
      SPRING_KAFKA_STREAMS_BOOTSTRAP_SERVERS: kafka:29092
      UIOT_METRICS_TOPIC: uiot-accounting
      UIOT_WINDOWS_TOPIC: uiot-accounting-windows
      UIOT_WINDOWS_SIZE: "1m"
    networks:
      - uiot
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--quiet", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      mongo:
        condition: service_healthy
      kafka-init-job:
        condition: service_completed_successfully

  uiot-service-connectivity:
    image: malczuuu/uiot-service-connectivity:${UIOT_VERSION}
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      SPRING_DATA_MONGODB_DATABASE: uiot-service-connectivity
      SPRING_KAFKA_STREAMS_BOOTSTRAP_SERVERS: kafka:29092
      UIOT_VHOST: /
      UIOT_ROUTING_KEY_TEMPLATE: telemetry.%s.%s
      UIOT_USERNAME_CONTEXT_SEPARATOR: \.
      UIOT_KAFKA_SYSTEM_EVENTS_TOPIC: uiot-system-events
    networks:
      - uiot
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--quiet", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      mongo:
        condition: service_healthy
      kafka-init-job:
        condition: service_completed_successfully

  uiot-service-history:
    image: malczuuu/uiot-service-history:${UIOT_VERSION}
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      SPRING_DATA_MONGODB_DATABASE: uiot-service-history
      SPRING_KAFKA_STREAMS_BOOTSTRAP_SERVERS: kafka:29092
      UIOT_THING_EVENTS_TOPIC: uiot-thing-events
      UIOT_THING_METADATA_TOPIC: uiot-service-history_thing-metadata
      UIOT_KEYED_THING_EVENTS_TOPIC: uiot-service-history_keyed-thing-events
      UIOT_SYSTEM_EVENTS_TOPIC: uiot-system-events
    networks:
      - uiot
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--quiet", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      mongo:
        condition: service_healthy
      kafka-init-job:
        condition: service_completed_successfully

  uiot-service-rooms:
    image: malczuuu/uiot-service-rooms:${UIOT_VERSION}
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      SPRING_DATA_MONGODB_DATABASE: uiot-service-rooms
      SPRING_KAFKA_STREAMS_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:29092
      UIOT_SYSTEM_EVENTS_TOPIC: uiot-system-events
    networks:
      - uiot
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--quiet", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      mongo:
        condition: service_healthy
      kafka-init-job:
        condition: service_completed_successfully

  uiot-service-rules:
    image: malczuuu/uiot-service-rules:${UIOT_VERSION}
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      SPRING_KAFKA_STREAMS_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATA_MONGODB_DATABASE: uiot-service-rules
      UIOT_SYSTEM_EVENTS_TOPIC: uiot-system-events
      UIOT_THING_EVENTS_TOPIC: uiot-thing-events
      UIOT_ACTION_EXECUTION_EVENTS_TOPIC: uiot-action-execution-events
    networks:
      - uiot
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--quiet", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      mongo:
        condition: service_healthy
      kafka-init-job:
        condition: service_completed_successfully

  uiot-service-telemetry:
    image: malczuuu/uiot-service-telemetry:${UIOT_VERSION}
    environment:
      SPRING_RABBITMQ_ADDRESSES: rabbitmq:5672
      SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka:29092
      UIOT_RABBITMQ_ROUTING_KEY_REGEXP: ^telemetry\.(.*)\.(.*)$$
      UIOT_RABBITMQ_ROUTING_KEY: telemetry.*.*
      UIOT_RABBITMQ_INPUT_QUEUE: uiot-telemetry-inbound
      UIOT_KAFKA_THING_EVENTS_TOPIC: uiot-thing-events
      UIOT_KAFKA_ACCOUNTING_TOPIC: uiot-accounting
    networks:
      - uiot
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--quiet", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      mongo:
        condition: service_healthy
      kafka-init-job:
        condition: service_completed_successfully

  uiot-service-things:
    image: malczuuu/uiot-service-things:${UIOT_VERSION}
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017
      SPRING_DATA_MONGODB_DATABASE: uiot-service-things
      SPRING_KAFKA_STREAMS_BOOTSTRAP_SERVERS: kafka:29092
      UIOT_CONNECTIVITY_INTEGRATION_URL: http://uiot-service-connectivity:8080/api/rooms/{roomUid}/things/{thingUid}/connectivity
      UIOT_SYSTEM_EVENTS_TOPIC: uiot-system-events
    networks:
      - uiot
    healthcheck:
      test: [ "CMD", "wget", "--spider", "--quiet", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      mongo:
        condition: service_healthy
      kafka-init-job:
        condition: service_completed_successfully

networks:
  uiot:

volumes:
  kafka_data:
  mongodb_data:
  rabbitmq_data:
