[versions]
spring-boot = "3.5.5"
problem4j-spring = "1.0.1"
springdoc-openapi = "2.8.13"
commons-codec = "1.20.0"

[libraries]

spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
problem4j-spring-bom = { module = "io.github.malczuuu.problem4j:problem4j-spring-bom", version.ref = "problem4j-spring" }
springdoc-openapi-bom = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc-openapi" }

commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }

# managed by spring-boot-dependencies
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-amqp = { module = "org.springframework.boot:spring-boot-starter-amqp" }
spring-boot-starter-data-mongodb = { module = "org.springframework.boot:spring-boot-starter-data-mongodb" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }

spring-kafka = { module = "org.springframework.kafka:spring-kafka" }

kafka-streams = { module = "org.apache.kafka:kafka-streams" }

junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-kafka-test = { module = "org.springframework.kafka:spring-kafka-test" }
spring-rabbit-test = { module = "org.springframework.amqp:spring-rabbit-test" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }

# managed by problem4j-spring-bom
problem4j-core = { module = "io.github.malczuuu.problem4j:problem4j-core" }
problem4j-spring-webmvc = { module = "io.github.malczuuu.problem4j:problem4j-spring-webmvc" }

# managed by springdoc-openapi-bom
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui" }
