[versions]
commons-lang3 = "3.19.0"
problem4j-spring = "1.1.6"
spotless = "8.0.0"
spring-boot = "3.5.7"
springdoc-openapi = "2.8.14"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
# managed by spring-boot-dependencies
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-amqp = { module = "org.springframework.boot:spring-boot-starter-amqp" }
spring-boot-starter-data-mongodb = { module = "org.springframework.boot:spring-boot-starter-data-mongodb" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-kafka = { module = "org.springframework.kafka:spring-kafka" }
commons-codec = { module = "commons-codec:commons-codec" }
kafka-streams = { module = "org.apache.kafka:kafka-streams" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-kafka-test = { module = "org.springframework.kafka:spring-kafka-test" }
spring-rabbit-test = { module = "org.springframework.amqp:spring-rabbit-test" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }

# managed by problem4j-spring-bom
problem4j-spring-bom = { module = "io.github.malczuuu.problem4j:problem4j-spring-bom", version.ref = "problem4j-spring" }
problem4j-core = { module = "io.github.malczuuu.problem4j:problem4j-core" }
problem4j-spring-webmvc = { module = "io.github.malczuuu.problem4j:problem4j-spring-webmvc" }

# managed by springdoc-openapi-bom
springdoc-openapi-bom = { module = "org.springdoc:springdoc-openapi-bom", version.ref = "springdoc-openapi" }
springdoc-openapi-starter-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui" }

# manually managed due to vulnerabilities in transitive dependency from spring-kafka
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commons-lang3" }
