server:
  port: 8334
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: uiot-service-room
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: uiot-service-room
  kafka:
    bootstrap-servers: localhost:9092
    streams:
      bootstrap-servers: "${spring.kafka.bootstrap-servers}"
    producer:
      client-id: "${spring.application.name}"
      bootstrap-servers: "${spring.kafka.bootstrap-servers}"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
  jackson:
    default-property-inclusion: non_null
springdoc:
  api-docs:
    path: /v3/api-docs
uiot:
  system-events-topic: uiot-system-events
