server:
  port: 8335
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: uiot-service-rule
  mongodb:
    uri: mongodb://localhost:27017
    database: uiot-service-rule
  jackson:
    default-property-inclusion: non_null
springdoc:
  api-docs:
    path: /v3/api-docs
uiot:
  system-events-topic: uiot-system-events
  thing-events-topic: uiot-thing-events
  action-execution-events-topic: uiot-action-execution-events
